src/IssueTracker/IssueTracker.WebUI/Controllers/IssuesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using IssueTracker.Common.Enumerations;
using IssueTracker.Common.Models;
using IssueTracker.Persistance;
using IssueTracker.WebUI.Models;
using IssueTracker.WebUI.TagHelpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace IssueTracker.WebUI.Controllers
{
    public class IssuesController : Controller
    {
        private readonly IssueTrackerContext _context;

        public IssuesController(IssueTrackerContext context)
        {
            _context = context;
        }

        [Authorize]
        public async Task<IActionResult> Index(SortState sortOrder = SortState.Column1, bool isDesc = true,  bool filter = false)
        {
            IQueryable<IssueEntity> issues = _context.Issues.Include(i => i.CreatedBy);
            if (filter)
            {
                issues = issues.Where(i => i.CreatedBy.Login == User.Identity.Name);
            }
            switch (sortOrder)
            {
                case SortState.Column1:
                    issues = isDesc ? issues.OrderByDescending(i => i.CreationDate) : issues.OrderBy(i => i.CreationDate);
                    break;
                case SortState.Column2:
                    issues = isDesc ? issues.OrderByDescending(i => i.ShortDescription) : issues.OrderBy(i => i.ShortDescription);
                    break;
                case SortState.Column3:
                    issues = isDesc ? issues.OrderByDescending(i => i.Status) : issues.OrderBy(i => i.Status);
                    break;
                case SortState.Column4:
                    issues = isDesc ? issues.OrderByDescending(i => i.Priority) : issues.OrderBy(i => i.Priority);
                    break;
                case SortState.Column5:
                    issues = isDesc ? issues.OrderByDescending(i => i.Urgency) : issues.OrderBy(i => i.Urgency);
                    break;
                case SortState.Column6:
                    issues = isDesc ? issues.OrderByDescending(i => i.CreatedBy.FullName) : issues.OrderBy(i => i.CreatedBy.FullName);
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(sortOrder), sortOrder, null);
            }

            var viewModel = new IssuesViewModel
            {
                Issues = await issues.ToListAsync(),
                SortModel = new IssueSortViewModel(sortOrder, isDesc, filter.ToString()),
                Caption = filter ? "Issues Created By You" : "All Issues"
            };
                
            return View(viewModel);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ShortDescription,Description,Priority,Urgency")] IssueEntity issueEntity)
        {
            if (ModelState.IsValid)
            {
                var user = await _context.Users.FirstOrDefaultAsync(u => u.Login == User.Identity.Name);
                issueEntity.CreatedBy = user;
                issueEntity.CreationDate = DateTime.Now;
                issueEntity.Status = IssueStatuses.New;
                var newRecord = new IssueTransitionEntity
                {
                    Command = TransitionCommands.Enter,
                    Issue = issueEntity,
                    MadeBy = user,
                    TransitionDate = DateTime.Now,
                    Comment = "Issue Created"
                };
                _context.Add(issueEntity);
                _context.Add(newRecord);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CreatedById"] = new SelectList(_context.Users, "Id", "FirstName", issueEntity.CreatedById);
            return View(issueEntity);
        }

        // GET: Issues/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var issueEntity = await _context.Issues
                .Include(i => i.CreatedBy)
                .Include(i => i.Transitions)
                .ThenInclude(t => t.MadeBy)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (issueEntity == null)
            {
                return NotFound();
            }
            var possibleCommands = issueEntity.GetPossibleActions();
            possibleCommands.Add(TransitionCommands.Save);
            ViewBag.PossibleActions = possibleCommands;
            return View(issueEntity);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ShortDescription,Description,Priority,Urgency")] IssueEntity issueEntity,
            string comment, TransitionCommands command = TransitionCommands.Save)
        {
            var currerntEntity = await _context.Issues.FirstOrDefaultAsync(i => i.Id == id);
            if (id != issueEntity.Id || currerntEntity == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {

            var user = await _context.Users.FirstOrDefaultAsync(u => u.Login == User.Identity.Name);
            var record  = new IssueTransitionEntity
            {
                MadeBy = user,
                Command = command,
                Issue = currerntEntity,
                TransitionDate = DateTime.Now,
                Comment = comment
            };
            _context.Add(record);

                currerntEntity.ShortDescription = issueEntity.ShortDescription;
                currerntEntity.Description = issueEntity.Description;
                currerntEntity.Priority = issueEntity.Priority;
                currerntEntity.Urgency = issueEntity.Urgency;
                currerntEntity.ChangeState(command);
                _context.Update(currerntEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.PossibleActions = issueEntity.GetPossibleActions();
            return View(issueEntity);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var issueEntity = await _context.Issues
                .Include(i => i.CreatedBy)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (issueEntity == null)
            {
                return NotFound();
            }

            return View(issueEntity);
        }

        // POST: Issues/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var issueEntity = await _context.Issues.SingleOrDefaultAsync(m => m.Id == id);
            _context.Issues.Remove(issueEntity);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

src/IssueTracker/IssueTracker.WebUI/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using IssueTracker.Common.Models;
using IssueTracker.Persistance;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IssueTracker.WebUI.Controllers
{
    public class UsersController : Controller
    {
        private readonly IssueTrackerContext _context;

        public UsersController(IssueTrackerContext context)
        {
            _context = context;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.Where(u => !u.IsDeleted).ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Login,FirstName,LastName,Password")] UserEntity userEntity)
        {
            if (await _context.Users.AnyAsync(u => u.Login == userEntity.Login))
            {
                ModelState.AddModelError("Login", "This Login is already in use, please pick another.");
            }
            if (ModelState.IsValid)
            {
                _context.Add(userEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userEntity);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userEntity = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            if (userEntity == null)
            {
                return NotFound();
            }
            return View(userEntity);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Login,FirstName,LastName,Password")] UserEntity userEntity)
        {
            if (id != userEntity.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userEntity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserEntityExists(userEntity.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userEntity);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userEntity = await _context.Users
                .SingleOrDefaultAsync(m => m.Id == id);
            if (userEntity == null)
            {
                return NotFound();
            }

            return View(userEntity);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userEntity = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            if (userEntity != null)
            {
                userEntity.IsDeleted = true;
                _context.Users.Update(userEntity);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(string login, string password)
        {
            var userEntity = await _context.Users.SingleOrDefaultAsync(m => m.Login == login && m.Password == password);
            if (userEntity != null)
            {
                await Authenticate(userEntity.Login);
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        private async Task Authenticate(string userName)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimsIdentity.DefaultNameClaimType, userName)
            };
            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }
        private bool UserEntityExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

src/IssueTracker/IssueTracker.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IssueTracker</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Issue Tracker</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li><a asp-action="Index" asp-route-filter="true" asp-controller="Issues">My Issues</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Issues <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a asp-area="" asp-controller="Issues" asp-action="Create">Add Issue</a></li>
                                <li><a asp-area="" asp-controller="Issues" asp-action="Index">All Issues</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a asp-area="" asp-controller="Users" asp-action="Create">Add User</a></li>
                                <li><a asp-area="" asp-controller="Users" asp-action="Index">All Users</a></li>
                            </ul>
                        </li>
                    </ul>

                    <div class="navbar-form navbar-right">
                        Hello, @User.Identity.Name | <a asp-controller="Users" asp-action="Logout">Logout</a>
                    </div>
                }
                else
                {
                    <form asp-controller="Users" asp-action="Login" id="signin" class="navbar-form navbar-right" role="form">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            <input id="login" type="text" class="form-control" name="login" value="" placeholder="Login">
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <input id="password" type="password" class="form-control" name="password" value="" placeholder="Password">
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                }
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - IssueTracker</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>